#pragma config(Sensor, dgtl11, liftDown,       sensorTouch)
#pragma config(Sensor, dgtl12, liftUp,         sensorTouch)
#pragma config(Motor,  port1,           leftFrontDrive, tmotorVex269, openLoop)
#pragma config(Motor,  port2,           rightIntake,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftLift,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rightOtherIntake, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           leftBackDrive, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           rightBackDrive, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           leftOtherIntake, tmotorVex269, openLoop)
#pragma config(Motor,  port8,           rightLift,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightFrontDrive, tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "autonomous.c"
#include "robothandlers.c"

#define ever (;;)

void pre_auton()
{

}

task autonomous()
{
	int trim = -10;
	//Put intake down
	motor[leftIntake] = -127;
	motor[rightIntake] = -127;
	wait1Msec(2800);
	motor[leftIntake] = -15;
	motor[rightIntake] = -15;

	//Drive Forward
	drive(127);
	wait1Msec(2400);
	drive(0);

	//Go Back while intaking
	motor[leftIntake] = 64;
	motor[rightIntake] = 64;
	wait1Msec(20);
	drive(-70,-70);
	motor[leftIntake] = 126;
	motor[rightIntake] = 126;
	wait1Msec(2200);
	motor[leftIntake] = trim;
	motor[rightIntake] = trim;

	//Go Back More
	drive(-127,-127);
	motor[leftIntake] = -127;
	motor[rightIntake] = -127;
	wait1Msec(100);
	motor[leftIntake] = 127;
	motor[rightIntake] = 127;
	wait1Msec(800);
	motor[leftIntake] = 10;
	motor[rightIntake] = 10;
	while(!SensorValue[liftUp]);
	drive(0);

	motor[leftIntake] = -127;
	motor[rightIntake] = -127;
	wait1Msec(500);
	motor[leftIntake] = 7;
	motor[rightIntake] = 7;
	//REALIGNMENT PERIOD
	while(!SensorValue[liftUp]);

	//Go Forward
	drive(127);
	wait1Msec(1550);
	drive(0);

	//Turn Left
	drive(-127,127);
	wait1Msec(803);
	drive(0);

	//Back Up
	drive(-127,-127);
	wait1Msec(1650);
	drive(0);

	//Put intake down
	motor[leftIntake] = -127;
	motor[rightIntake] = -127;
	wait1Msec(2200);
	motor[leftIntake] = trim;
	motor[rightIntake] = trim;

	//Go Forward
	drive(127);
	wait1Msec(5250);
	drive(0);

	//Intake stuff
	drive(-15);
	wait1Msec(200);
	drive(0);
	motor[leftIntake] = 127;
	motor[rightIntake] = 127;
	wait1Msec (3000);
	motor[leftIntake] = 0;
	motor[rightIntake] = 0;

	//Go Forward
	drive(64);
	wait1Msec(305);
	drive(0);

	//Point turn
	drive(127 , -127);
	wait1Msec(931);
	drive(0);

	//Align (aka slam into wall)
	drive(-127,-127);
	wait1Msec(3000);
	drive(0);

	//Put intake down
	motor[leftIntake] = -127;
	motor[rightIntake] = -127;
	wait1Msec(2000);
	drive(127);
	wait1Msec(600);
	motor[leftIntake] = -10;
	motor[rightIntake] = -10;

	//Go Forward
	wait1Msec(2600);
	drive(0);

	//Intake
	motor[leftIntake] = 127;
	motor[rightIntake] = 127;
	wait1Msec (2600);
	motor[leftIntake] = 0;
	motor[rightIntake] = 0;

	//Intake
	motor[leftIntake] = -127;
	motor[rightIntake] = -127;
	wait1Msec (1500);
	motor[leftIntake] = 0;
	motor[rightIntake] = 0;

	//SCORE
	motor[leftLift] = 127;
	motor[rightLift] = 127;
	motor[leftOtherIntake] = 127;
	motor[rightOtherIntake] = 127;
	wait1Msec(13000);
	motor[leftLift] = 0;
	motor[rightLift] = 0;
	motor[leftOtherIntake] = 0;
	motor[rightOtherIntake] = 0;

	//Run-Away!
	motor[leftLift] = -127;
	motor[rightLift] = -127;
	motor[leftOtherIntake] = -127;
	motor[rightOtherIntake] = -127;
	wait1Msec(8000);
	drive(-127,-127);
	wait1Msec(500);
	drive(-127,-126);
	wait1Msec(1500);
	motor[leftLift] = 0;
	motor[rightLift] = 0;
	motor[leftOtherIntake] = 0;
	motor[rightOtherIntake] = 0;
	drive(0);



}

task usercontrol()
{
		StartTask(intakeHandler,0);
		StartTask(liftHandler,0);
		StartTask(driveHandler,0);
		StartTask(intakeAutos,0);
		StartTask(liftAutos,0);
}