#pragma config(Sensor, dgtl1,  liftUpBtn,      sensorTouch)
#pragma config(Sensor, dgtl2,  liftDownBtn,    sensorTouch)
#pragma config(Sensor, dgtl3,  intakeDownBtn,  sensorTouch)
#pragma config(Motor,  port1,           leftFrontDrive, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port2,           leftBackDrive, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           rightFrontDrive, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           rightBackDrive, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           rightLift,     tmotorVex269, openLoop)
#pragma config(Motor,  port7,           intakeLeft,    tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port8,           intakeRight,   tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "pid.c"
#include "robotHandlers.c"

//Called before game starts
void pre_auton()
{
  bStopTasksBetweenModes = true;
}

//20 second autonomous
task autonomous()
{
	AutonomousCodePlaceholderForTesting(); 
}

//120 second usercontrol
task usercontrol()
{
	StartTask(driveHandler);
	StartTask(liftHandler);
	StartTask(intakeHandler);
}