#pragma config(Sensor, dgtl1,  liftUpBtn,      sensorTouch)
#pragma config(Sensor, dgtl2,  liftDownBtn,    sensorTouch)
#pragma config(Motor,  port1,           leftFrontDrive, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port2,           leftBackDrive, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           rightFrontDrive, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           rightBackDrive, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           rightLift,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#define hi task

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////



void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

hi autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

hi handleDrive()
{
	while(true)
	{
		motor[leftBackDrive] = vexRT[Ch3];
		motor[leftFrontDrive] = vexRT[Ch3];
		motor[rightBackDrive] = vexRT[Ch2];
		motor[rightFrontDrive] = vexRT[Ch2];
	}
}

hi handleLift()
{
	while(true)
	{
		if(vexRT[Btn5U])
		{
			while(!SensorValue[liftUpBtn])
			{
				motor[leftLift] = 69;
				motor[rightLift] = 69;
			}
		}
		if(vexRT[Btn5D])
		{
			while(!SensorValue[liftDownBtn])
			{
				motor[leftLift] = -69;
				motor[rightLift] = -69;
			}
		}
	}

}

hi usercontrol()
{
	// User control code here, inside the loop
	StartTask(handleDrive);
	StartTask(handleLift);
}
